use strict
akashic-games/pdi-browser pull request #107
Opened 2021-01-19 10:51 UTC by kamakiri01

## このPullRequestが解決する内容

`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。

2021-01-19 11:01 UTC, kamakiri01 commented on src/Platform.ts
> +		return undefined;
存在しない `MasterVolume` の扱いが `undefined` で良いかは確認したいです。

2021-01-21 02:38 UTC, xnv requested changes
全箇所確認していませんが、コメントのとおり全体的に `!` の扱いについて再考をお願いしたいです。

2021-01-21 02:38 UTC, xnv commented on src/Platform.ts
> +		return undefined;
`_audioManager` が存在しない状況ってなさそうですし、そもそもこの if 文いらないのでは。

安全を期すなら `0` でもいいと思いますが、その場合 TODO コメント (おそらく不要な生存チェックなので) を残しておきたいです。

2021-01-21 02:38 UTC, xnv commented on src/utils/XHRLoader.ts
> +				callback(null!, response);
これは強引に non-null 扱いせず、 `get()` や  `getArrayBuffer()` の `callback` の `error` に `| null` をつける方が正着ではありませんか。

2021-01-21 02:38 UTC, xnv commented on src/plugin/WebAudioPlugin/WebAudioPlayer.ts
> +		this._sourceNode = undefined!;
これも `!` せず型に `| null` がつく方が妥当では？　再生されるまで存在しないですし、現実 `_sourceNode` の値で分岐している箇所があります。

もしかすると (TS の型推論力によっては) https://github.com/akashic-games/pdi-browser/pull/107/files#diff-29b5e84d453be88013c46e9bb4cad2801a8dd31bdc0d0565900aae1aaf3911c9R48-R52 このへんで if チェックしてないのが問題になるかもしれませんが、その場合は `bufferData.start(0)` とかに変えればいいと思います。

2021-01-21 02:38 UTC, xnv commented on src/plugin/WebAudioPlugin/WebAudioAsset.ts
> +		return null!;
これ現実的に通過しないパスなのでどっちでもいいんですが、強いて言えば `path` そのまま `return` するのがいいような？ (つけるべき拡張子がなければ素通し; エラーになるにしても null よりはわかりやすいリクエストになる)

2021-01-21 02:38 UTC, xnv commented on src/plugin/WebAudioPlugin/WebAudioAsset.ts
> +	_lastPlayedPlayer: pdi.AudioPlayer = null!;
これも、強引に non-null 扱いするのではなく、元の型を正す (`| null` にする) べきに思います。

全体的に「正常系の動作の中で nullable であるなら、型も nullalbe にする」のを基本としたいです。そうでないと型検査の信頼性を損なうからです。

基本、次のどれかにしたいです:

- 型に `| null` をつけ、利用箇所では生存チェックをする
- 代入時に `!` をつける (型上は常に non-null 扱いする)
  - constructor で必ず初期化され、 `destroy()` でしかクリアされないなど、正常系では non-null 扱いできるもの
  - (言い換えると、「 destroy() 後にそのプロパティを触る異常系のためだけに、正常系の型チェック処理を増やすことはしない」)
- 代入時に `!` をつけ、背景を補足するコメントをつける
  - 他リポジトリの I/F の都合上どうしても `!` をつけないといけないなど

2021-01-21 04:09 UTC, kamakiri01 commented on src/Platform.ts
> +		return undefined;
`if` で振り分けられている理由が分からなかったので元の処理を残しました。実際はコンストラクタで必ず `new` されるはずで、外部からの削除も想定していないように見えるので、単に `getMasterVolume()` 結果を返すようにします。

2021-03-05 12:07 UTC, kamakiri01 commented
https://github.com/akashic-games/pdi-browser/pull/108 同様、こちらもクローズします。
strict 対応は、個別の strict フラグに対して行います。

2021-03-05 12:07 UTC, closed without merging