use strict
akashic-games/pdi-browser pull request #108
Opened 2021-01-21 14:18 UTC by kamakiri01

https://github.com/akashic-games/pdi-browser/pull/107 の non-null 修正です。

## このPullRequestが解決する内容

`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。

2021-01-21 14:25 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +	const context = canvas.getContext("2d")!;
`getContext()` が得られないケースはクラスのハンドリング責務を超えると思い `!` を許しています。

2021-01-21 19:11 UTC, xnv requested changes

2021-01-21 19:11 UTC, xnv commented on src/canvas/GlyphFactory.ts
> +	isSurfaceValid?: boolean
この差分必要でしょうか。そもそもこのファイル内でしか呼び出せないでしょうし、二箇所の呼び出し元どちらも全引数指定していそうです。

2021-01-21 19:11 UTC, xnv commented on src/canvas/CanvasSurface.ts
> +		if (this.canvas) {
すぐ下で `!` つけているとおり non-nullable として扱うなら (それでよいと思うのですが) 、ここの if チェックは不要では。

2021-01-21 19:11 UTC, xnv commented on src/asset/XHRTextAsset.ts
> +	data: string = "";
ここ変えても `pdi.TextAsset` を変えないと `undefined` の線は実質消えない上、ゲーム開発者に見える挙動が微妙に変わってしまっていませんか。

2021-01-26 12:21 UTC, kamakiri01 commented on src/asset/XHRTextAsset.ts
> +	data: string = "";
pdi-typesに修正を入れます。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/CanvasSurface.ts
> +		if (this.canvas) {
不要でした。削除します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +	isSurfaceValid?: boolean
pdi-typesの `calcGlyphArea()` の型がこれらを任意にしているので、それに合わせています。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/shims/SurfaceFactory.ts
> +		if (RenderingHelper.usedWebGL(rendererCandidates) && !!this._shared) {
確かに挙動として不自然です。コメントで仕様を付記します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
>  	private _uniformSetterTable: { [type: string]: (loc: WebGLUniformLocation, v: number | Int32Array | Float32Array) => void; };
直します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/webgl/WebGLTextureAtlas.ts
> +		if (map) this._register(shared, map, surface._drawable); // mapが無い場合insertできていない
🙇‍♂️ 
`!` を付けてコメントを残します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/webgl/WebGLTextureAtlas.ts
> +			if (map) {
`!` 追加します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/canvas/webgl/WebGLTextureMap.ts
> +	insert(surface: pdi.Surface): WebGLTextureMap | undefined { // Array#shift() の型に合わせる
はい、コメントいただいた方針で `| undefined` は消すことができます。対応します。

2021-01-26 12:21 UTC, kamakiri01 commented on src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
>  	private _dummyDurationWaitTimer: any;
ファイル単位で揃えます。

2021-01-26 12:21 UTC, kamakiri01 commented on src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
> +			if (this._audioInstance)this._audioInstance.pause();
コメント残して `!` にします。

2021-01-26 12:21 UTC, kamakiri01 commented on src/plugin/WebAudioPlugin/WebAudioPlayer.ts
> +	private _sourceNode: AudioBufferSourceNode | null = null;
合わせます。

2021-01-26 12:21 UTC, kamakiri01 commented on src/plugin/HTMLAudioPlugin/HTMLAudioAsset.ts
> +					++this._intervalCount!; //
削除します。

2021-01-27 03:11 UTC, kamakiri01 commented on src/asset/XHRTextAsset.ts
> +	data: string = "";
すみません、pdi-types側への修正は影響が広くなるので `null!` で対応します。

2021-01-27 04:31 UTC, yu-ogi reviewed
全体的に `!` を使って単にコンパイルを通すだけの対応が多い印象を受けました。
この方針で進めるとしたら、後続として「`!` を使っている箇所を是正する」という対応が別途必要になるかと思います。

2021-01-27 04:31 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +	private _deleteRequestedTargets: RenderTarget[] = [];
[こちらのドキュメント](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization) によるとメンバ変数に `!` をつけるのが正道なようです。

2021-01-27 04:31 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +		this._currentShaderProgram.set_uAlpha(this._currentAlpha!);
`this._currentColor` や `this._currentAlpha` には結局どのような型が入っているのでしょう。`!` で型が握りつぶされている箇所が多すぎて、もはや strict を有効にしている意味が無いように思います。

2021-01-27 05:02 UTC, xnv commented on src/canvas/shims/SurfaceFactory.ts
> +	 * このメソッドが呼び出される前に、createPrimarySurface() が呼ばれている必要がある
それも検討したんですがまあコメントで良かろうか……という背景です: https://github.com/akashic-games/pdi-browser/pull/108/files#discussion_r562121864

2021-01-27 05:49 UTC, xnv commented on src/canvas/GlyphFactory.ts
> +	isSurfaceValid?: boolean
ええと…… pdi-types に `calcGlyphArea()` はないと思いますが、「 `calcGlyphArea()` の戻り値 `GlyphArea` (これは pdi-types にある)  で、いくつかのプロパティが  optional であるから」ということですかね。

しかしそもそも、これで strict 通っているでしょうか？　というのも、この関数の戻り値  `pdi.Glyph` の `width` プロパティは `number` になっていますが、この状態では `undefined` が入ってしまう可能性があるように見えます。この差分は引数の型制限を「緩めて」型を合わせているわけですが、それによって関数の戻り値の型の strict 性が怪しくなってしまっていそうです。

型制限を「緩めて」合わせるのではなく、ここに渡される値の出元 (＝ `calcGlyphArea()` の戻り値) の型を「厳密に」記述する方が正道ではないでしょうか。それはつまり `GlyphArea` の派生クラスを定義して、 `width`, `height` を non-nullable に限定するなどした上で、 `calcGlyphArea()` はそれを返すようにする、ということなんですが。

問題の根源は `calcGlyphArea()` の返している型が `pdi.GlyphArea` とマッチしていないことだと思いますし、 `calcGlyphArea()` は pdi-browser が内部的に使っているだけの関数で、 pdi-types に縛られる必要はないからです。

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +		this._currentShaderProgram.set_uAlpha(this._currentAlpha!);
「どこまでstrictにするか」という点でPRの説明に書いておらず申し訳ないですが、「strict有効にしてビルドが通る」「`!` が無くてもstrictになるよう各種修正を加える」は分けて作業したいと考えています。
別リポジトリに影響が及ぶ、または設計変更が必要な修正が入る場合、それは本質的にはstrict化とは別の課題として扱ったほうが良いだろうと思うからです。（PRの規模を大きくしすぎたくない、という意図もあります）

そのためこのPRでは、TODOコメントや旧挙動を維持するための `!` のような「厳密にはstrictではない」実装が残りうる想定で作業をしています。前提の共有が無くてすみません。

それはそれとして、この箇所の `!` は不要になっています。削除します。

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +	private _deleteRequestedTargets: RenderTarget[] = [];
資料ありがとうございます。 init分割パターンだとこれで nullable 回避できるんですね。

読んで知りましたが、このドキュメントのサンプルコード、実行してみると`initialize` でfooを初期化しなくてもエラーにならないんですね…。

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +					loc: this._context.getUniformLocation(this.program, k) || {}
loc を nullable にする場合、`updateUniforms()` の `cache.update()` 時に loc 存在チェックを入れる、ということで良いでしょうか。

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +		if (!this._uniforms) return;
`_uniforms` は `WebGLShaderProgram` コンストラクタの正常系で `uniform` が渡されないケースがあり、 `updateUniforms()` が呼ばれるパスがあるので例外を投げると影響がありそうです。
（なぜ今までエラーになっていなかったのか分からないのですが…）

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +			glyphArea = calcGlyphArea(result.imageData!);
`createGlyphRenderedSurface` の7番目の引数に `true` を渡しているので、 `createGlyphRenderedSurface` の型の上では `imageData ?` になりますが実利用では `imageData` を必ず受け取ることができます。

`createGlyphRenderedSurface` を利用箇所ごとに分けてしまえば型の上で `!` は不要になりますが、このファイル内に閉じた仕様なので、関数の共通化と天秤にして `!` を使って良いだろうかと思っています。

読み手にコストをかける点では良くない状態なのでコメントを追加します。

2021-01-27 12:46 UTC, kamakiri01 commented on src/asset/XHRTextAsset.ts
> +	data: string = null!;
XHRTextAsset ユーザから見える挙動が変わるので、維持の点では `null!` または `undefined!` が良いだろうかと思いました。（strict性とトレードオフになり、どう倒すか悩ましいのですが………）

2021-01-27 12:46 UTC, kamakiri01 commented on src/asset/XHRScriptAsset.ts
> +		this.script = "";
`XHRTextAsset` で `null!` に寄せたのでこちらも同様にしようと思います。

2021-01-27 12:46 UTC, kamakiri01 commented on src/ContainerController.ts
> +		this.inputHandlerLayer._inputHandler!.setScale(xScale, yScale); // initialize()で_inputHandler代入済みとする
L96では `_inputHandler` がまだ nullable なので `!` を使っています。
実ユースケースとしては `initialize()` → `setRootView()`で `_inputHandler` は代入されていますが、これを型の上で解消するのは後続の検討としたいです。

2021-01-27 12:46 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +	isSurfaceValid?: boolean
すみません `calcGlyphArea()` の戻り値 `GlyphArea` です。
`interface GlyphArea extends pdi.GlyphArea` を定義して使うようにします。

2021-01-27 12:55 UTC, kamakiri01 commented on src/ContainerController.ts
> +		if (!this._rendererReq) return;
周辺でこの辺りの扱いが `if-return` と `throw` 混ざっていて悩ましいのですが、 _rendererReq` については実利用では `initialize()` → `setRootView()` されるので例外に到達することはなさそうでした。
型の上で `_rendererReq` をnon-nullにすればバリデーション自体不要になると思いますが、今後の検討にしたいです。

2021-01-28 01:50 UTC, yu-ogi commented on src/canvas/webgl/WebGLShaderProgram.ts
> +		if (!this._uniforms) return;
あ、`this.uniforms` の値に関わらず呼ばれるんですね。失礼しました。
現状でエラーが発生しないのは `this.uniforms == null` であれば `this.uniformCaches.length === 0` なので `this.uniforms` の参照までコードが実行されないためですね。

2021-01-28 02:01 UTC, yu-ogi commented on src/canvas/webgl/WebGLShaderProgram.ts
> +					loc: this._context.getUniformLocation(this.program, k) || {}
少なくとも上記の対応だと別の影響がありそうなので以下のいずれかの対応が必要そうです。
1. loc の参照時に都度存在チェックをする
   * loc の値が更新されることはないのでメリットが少ない
2. この時点で loc が null であれば uniform を登録せず、ログを出力して処理は続ける (穏健派)
3. この時点で loc が null であれば例外を投げる (過激派)

strict を有効にしたことで生じた懸念をコード内に残しておきつつ、既存の動作には影響を与えないという意味では個人的に 2. の対応が良いかなと思います。

2021-01-28 02:12 UTC, yu-ogi commented on src/canvas/CanvasSurface.ts
> +		if (!this.canvas) return;
この差分は不要そう?

2021-01-28 02:12 UTC, yu-ogi commented on src/canvas/GlyphFactory.ts
> +		const context = canvas.getContext("2d")!;
別でもコメントしましたが context のチェックは必要かと思います。

2021-01-28 02:12 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +		const texture = context.createTexture()!;
少なくとも null の場合のログは出したほうが良いかと思います。

2021-01-28 02:12 UTC, yu-ogi commented on src/asset/HTMLImageAsset.ts
> +	hint: pdi.ImageAssetHint | undefined = undefined;
` = undefined` は不要かと思います。

2021-01-28 13:37 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +	const context = canvas.getContext("2d")!;
resolveで見落としていました。参考にcontextチェックを入れます。

2021-01-28 13:37 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +					loc: this._context.getUniformLocation(this.program, k) || {}
ありがとうございます。
既存の挙動を維持したい点で2の方針で修正をします。

2021-01-28 13:37 UTC, kamakiri01 commented on src/canvas/CanvasSurface.ts
> +		if (!this.canvas) return;
不要になっています。削除します。

2021-01-28 13:37 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +		const context = canvas.getContext("2d")!;
追加します。

2021-01-28 13:37 UTC, kamakiri01 commented on src/asset/HTMLImageAsset.ts
> +	hint: pdi.ImageAssetHint | undefined = undefined;
不要です。削除します。

2021-01-28 13:49 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +		const texture = context.createTexture()!;
同じ処理でthrowされているためそちらに揃えます。

2021-02-01 04:31 UTC, xnv commented on src/canvas/GlyphFactory.ts
> +    advanceWidth?: number;
インデントずれてます。

2021-02-08 13:36 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +    advanceWidth?: number;
直します 🙇‍♂️

2021-02-09 07:00 UTC, yu-ogi reviewed
いくつかコメント対応が漏れているようでして、ご確認いただけたらと思います。

2021-02-09 12:23 UTC, kamakiri01 commented on src/Platform.ts
> +			getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()
> 外部メソッドなので

外部（この場合は `InputHandlerLayer` ？）がメソッド利用の責務を持つべき、ということでしょうか。
この箇所の場合は、 `getScale()` にアロー関数を返しているので、評価タイミングによっては `_inputHandler` が不存在のままでも正常系が成立するI/Fにも読めます。（それが筋が良いかは別だと思いますが…）
こういった場合例外を投げて良いか伺いたいです。

2021-02-09 12:23 UTC, kamakiri01 commented on src/ResourceFactory.ts
> +		const activePlugin = this._audioPluginManager.getActivePlugin()!; // 利用側でtryInstallPlugin()が事前に呼ばれているためnon-nullとして扱う
追記します。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +			throw new Error(msg!);
出力するようにします。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +		if (!program) throw new Error("WebGLShaderProgram#_makeShaderProgram cannot create Program.");
同じ形式に揃えます。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +					console.log("WebGL UniformLocation is undefined. cache skipped.");
出力冒頭に追加します。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +	texture: WebGLTexture | null;
`_init()` での null 初期化に対応しています。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLTextureAtlas.ts
> +				var canvasContext = canvas.getContext("2d")!;
うっ、対応漏れですすみません。null 判定追加します。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/webgl/WebGLTextureAtlas.ts
> +			map = maps.shift()!; // maps.lengthは1以上を期待できるので、Shift() は undefined を返さないと仮定する
直前で `>=` 取っているので自明ということでコメント削除します。

2021-02-09 12:23 UTC, kamakiri01 commented on src/utils/XHRLoader.ts
> +				callback(null!, response);
`callback(error?, data?)` に直します。

2021-02-09 12:23 UTC, kamakiri01 commented on src/canvas/GlyphFactory.ts
> +									strokeColor: string, strokeOnly: boolean, fontWeight: pdi.FontWeightString): GlyphRenderSurfaceResult {
tslint の `parameters are not aligned` に沿った修正ですが、そもそも tslint から移行するのが筋だと思うので、 eslint 移行することで解決したいです。

2021-02-10 00:02 UTC, yu-ogi commented on src/Platform.ts
> +			getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()
外部メソッドというのは `Platform#getOperationPluginViewInfo()` (または戻り値の `getScale()`) を指していました。これらは pdi-browser の外部から呼ばれるので `inputHandlerLayer` が存在しない理由を明示しておいたほうが良いのではという意図でした。

```javascript
getOperationPluginViewInfo(): .. {
  if (!this.containerController.inputHandlerLayer || ...) {
    throw new Error("事前に Platform#setRendererRequirement() を呼ぶ必要がある");
  }
  return {
    view: ...
    getScale: () => ...
  }
```

2021-02-10 00:15 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +	texture: WebGLTexture | null;
`_init()` で初期化しているのはプライマリサーフェス (= framebuffer や texture が存在しない) なのでこれらの値が null (undefined) となるのは自然ですが、一方でバックサーフェスとして利用される `WebGLSharedObject#createRenderTarget()` の戻り値に null が渡されるのは異常系となるので、`WebGLSharedObject#_renderTarget` とは型を分けてしまうという方針のほうが自然な気がします。

実際↓の箇所で本来不要な条件が追加されてしまっているようです。
https://github.com/akashic-games/pdi-browser/blob/78201a0ed2c9d2be90bf80ff0f33cabf89dff43a/src/canvas/webgl/WebGLSharedObject.ts#L152

2021-02-10 08:40 UTC, kamakiri01 commented on src/Platform.ts
> +			getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()
なるほど、確かに現状では外部に例外発生時の理由を示す手段が無いです。

`getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()` を改めて、

```
getScale: () => {
	if (!this.containerController.inputHandlerLayer || !this.containerController.inputHandlerLayer._inputHandler) {
		throw new Error("call Platform#setRendererRequirement() before getScale()");
	}
	return this.containerController.inputHandlerLayer._inputHandler.getScale();
}
```
とすれば、 `getScale()` を呼ぶ前に `Platform#setRendererRequirement()` を呼ぶ必要があることを示しつつ、 `Platform#getOperationPluginViewInfo()` を呼ぶタイミングはそれよりも先行して良いという既存の実装を変更せずに済むのではと思いますが、どうでしょうか。

2021-02-24 11:48 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +	texture: WebGLTexture | null;
non-Null な `RenderTarget` 型を追加して `WebGLSharedObject#createRenderTarget` の戻り値の型にします。

2021-02-24 12:04 UTC, kamakiri01 commented on src/InputHandlerLayer.ts
> +		if (!this._inputHandler) return;
`setOffset` が `this._inputHandler` の生成前に呼ばれてはならないことを示すための例外、という理解であっているでしょうか。
 （呼び出し順序の取り決めをこのメソッドが示す必要があるのか、という辺りで例外は強すぎるのではないかという気持ちがあり、そのまま return させても良いのではないかとも思えています）

2021-02-25 03:17 UTC, yu-ogi commented on src/Platform.ts
> +			getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()
すいません、色々書いたあとに恐縮ですが non-null operation (`!`) ではなく optional chaining (`?.`) を使えばそれで良いような気がしました。

2021-02-25 03:53 UTC, yu-ogi commented on src/canvas/webgl/WebGLShaderProgram.ts
> +			throw new Error(msg!);
こちらも同様の修正をしておきたいです。

2021-02-25 03:53 UTC, yu-ogi commented on src/canvas/webgl/WebGLShaderProgram.ts
> +				throw new Error("unknown error");
`WebGLShaderProgram#...` という情報は入れておきたいです。

2021-02-25 03:53 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
インタフェース名があまりにも strict 対応に引っ張られている印象があり、一見すると意味がわからないような気がします。既存の `RenderTarget` はそのままで、`framebuffer` と `texture` を削ぎ落としたインタフェースを `PrimaryRenderTarget` とでもした方が良さそうに思いました。

2021-02-25 03:53 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
型の不一致が起きてしまっているので `this._currentAlpha: number | null` とすべきかと思います。

2021-02-25 03:53 UTC, yu-ogi commented on src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
> +			this._audioInstance!.pause(); // _isStopRequested が真の場合 _audioInstance も存在する
optional chaining (`?.`) ではだめなのでしょうか。

2021-02-25 03:53 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +	private _deleteRequestedTargets!: RenderTarget[];
ここだけメンバ変数に `!` をつける方針なのは何か理由があるのでしょうか。

2021-03-01 12:22 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +	private _deleteRequestedTargets!: RenderTarget[];
このファイル内で `!` に揃えます。

2021-03-01 12:22 UTC, kamakiri01 commented on src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
> +			this._audioInstance!.pause(); // _isStopRequested が真の場合 _audioInstance も存在する
`?` で解決できそうです。

2021-03-01 12:22 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
指摘貰って気付きましたが、 `_init()` で初期化・代入される変数なので、 `private _currentAlpha!: number;` に揃えるほうが良さそうに思います。

2021-03-01 12:22 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +				throw new Error("unknown error");
追加します。

2021-03-01 12:22 UTC, kamakiri01 commented on src/canvas/webgl/WebGLShaderProgram.ts
> +			throw new Error(msg!);
```
if (msg) {
	throw new Error(msg);
} else {
	throw new Error("WebGLShaderProgram#_makeShader: unknown error");
}
```
にします。

2021-03-01 12:22 UTC, kamakiri01 commented on src/Platform.ts
> +			getScale: () => this.containerController.inputHandlerLayer!._inputHandler!.getScale()
あっ、確かにそうですね。 `?` にします。

2021-03-01 12:24 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
`RenderTargetNonNull ` は良い名前を付けられなかったためですが、インターフェイスを減らした `PrimaryRenderTarget ` は
```
getPrimaryRenderTarget(width: number, height: number): PrimaryRenderTarget {
	return this._renderTarget;
}
``` 
として使う、ということでしょうか。

2021-03-01 12:46 UTC, kamakiri01 commented on src/Platform.ts
> +		return this.containerController.surface!; // 親pdiのI/Fに合わせる
例外を投げます。

2021-03-02 00:59 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
いえ、それは「`null` が `_init()` 以外の箇所で代入されることが無い変数」のみに当てはまる条件かと思います。

2021-03-02 01:14 UTC, yu-ogi commented on src/canvas/context2d/Context2DSurface.ts
> +	protected _context: CanvasSurfaceContext = null!;
`| null` とすべき箇所かと思います。

2021-03-02 01:14 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
はい。そのようなイメージです。

2021-03-02 01:14 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +			framebuffer: null,
これはできればセルフレビューで気づいてほしいです。

2021-03-02 01:14 UTC, yu-ogi commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
`createPrimarySurface(width, height, this._rendererCandidates ?? undefined)` や if で分岐する方針ではだめなのでしょうか。型の不一致を頑なに `!` で許容するメリットが良くわかっていないです。

2021-03-02 01:14 UTC, yu-ogi commented on src/asset/XHRScriptAsset.ts
> +	script: string = undefined!;
このあたりも `script!: string` で良いのでは。全体的にポリシーを統一しておいたほうがわかりやすいかなと思います。

2021-03-02 05:02 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
なるほどです。
ただ、 `RenderTarget` 自体のインターフェイスを減らすと `WebGLBackSurface` など込みで `PrimaryRenderTarget` `RenderTarget` を併存させる処理が必要になりそうです。  strict対応のPRで `WebGLRenderer` の絡む大きな変更を入れることには抵抗があり、別の修正として行いたいです。

2021-03-02 05:02 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
はい、そうしないと多分tscがエラーを出すと思います。_init() で代入されるメンバに対しての意見です。

2021-03-02 05:02 UTC, kamakiri01 commented on src/canvas/context2d/Context2DSurface.ts
> +	protected _context: CanvasSurfaceContext = null!;
`_context` を触る `changePhysicalScale()` のユーザが `ContainerController#changeScale()` のみなので `null` にしても大丈夫そうです。（ `InputAbstractHandler#setScale()` の`getScale()` ユーザ挙動までは追い切れていませんが…)
`| null` に修正します。

2021-03-02 05:02 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +			framebuffer: null,
エディタ側で保存漏れでした。指摘ありがとうございます。

2021-03-02 05:02 UTC, kamakiri01 commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
このコメントを貰った箇所に限らない話ですが、このPRのスコープとして、descriptionに書いたように「strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。」を想定しているためです。（おそらくこの「可能な是正」の程度に認識差異があると思っています）

2021-03-02 05:03 UTC, kamakiri01 commented on src/asset/XHRScriptAsset.ts
> +	script: string = undefined!;
ファイル単位では揃えていますが、リポジトリ全体は統一できていないです。（null or undefined辺りも統一したいところです）
この箇所は修正します。

脱線しますがこの `script` メンバ、 `_load()` が即時呼ばれる保証が（pdi-browserのコード内には）無さそうなので、本当に `!` で良いのかは少し不穏ですね。

2021-03-03 05:54 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
コメントの意味がよくわかっていないのですが `this._currentAlpha: number | null` としていない理由は何でしょう?

2021-03-03 06:00 UTC, yu-ogi commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
つまり `RenderTargetNonNull` というインタフェース名を (一時的にも) 許容するという意味でしょうか。少なくとも master ブランチに入れるのは抵抗があります。

2021-03-03 06:10 UTC, yu-ogi commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
仰る意味はわかるのですが、後からどうやって是正するのでしょう。「リポジトリ内の `!` をすべて検索してそれが non-null assertion であるかを人の目で判断して修正する」というのはあまりにも不毛ですし、それであれば tsconfig.json の strict は無効のままにして、部分的に対応していったほうが良いのではないかと思います。

2021-03-03 06:22 UTC, yu-ogi commented on src/asset/XHRScriptAsset.ts
> +	script: string = undefined!;
> 脱線しますがこの script メンバ、 _load() が即時呼ばれる保証が（pdi-browserのコード内には）無さそうなので、本当に ! で良いのかは少し不穏ですね。

現実的には、ゲームコンテンツからの読み込み時点で既に `_load()` が呼ばれているはず (これは akashic-engine 側の実装仕様) なので、初期値が何であれ影響はないかと思います。

2021-03-03 13:04 UTC, kamakiri01 commented on src/asset/XHRScriptAsset.ts
> +	script: string = undefined!;
はい、現状のpdi-browser開発者にとってakashic-engine側の仕様なのは割と自明ですが、コメントを付けておくのが親切かもしれません。（そういったコメントはメンテナンスから漏れがちかもしれませんが…）

2021-03-03 13:05 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +export interface RenderTargetNonNull {
このコメントスレッドの中で、いま2つの話題があると思っていて、 `PrimaryRenderTarget` インターフェイスの採用とそれに伴う修正については別の修正として行いたいです。 `RenderTarget ` を扱う処理自体の変更が必要になるためです。

一方で、 `RenderTargetNonNull ` については、
> （もう少し妥当な名前にしたいです）

https://github.com/akashic-games/pdi-browser/pull/108#discussion_r584669561
の通り、もっと良い名前にしたいと考えています。良い名前がすぐに出ませんが `FixedRenderTarget` とかですかね…。

https://github.com/akashic-games/pdi-browser/pull/108#discussion_r573345604 でいただいたコメントには反しますが、 `createRenderTarget()` の戻り値の型を `RenderTarget` のままにすれば、そもそもこの `RenderTargetNonNull ` インターフェイスは入れる必要が無くなります。

2021-03-03 13:05 UTC, kamakiri01 commented on src/canvas/webgl/WebGLSharedObject.ts
> +			this._currentAlpha = null!;
コメントの「型の不一致」というのは、 `this.draw()` で `null!` を代入しているため nullable なので `this._currentAlpha: number | null` とすべき、ということで良いでしょうか。

`this._currentAlpha` は `this.begin()` で `this._currentShaderProgram.set_uAlpha(this._currentAlpha)` に渡されるメンバです。そのため ` this._currentAlpha: number | null` とすると、ここに null 判定を追加する必要があります。
ですが `this.draw()` での null 代入は一時的なもので、 `this._currentAlpha` の null は他の状態から参照されないため、 `| null` 型のバリデーションは常に non-null です。

2021-03-03 13:06 UTC, kamakiri01 commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
> 後からどうやって是正するか

このPRの差分でおおよそのnon-null assertion箇所を拾うことはできると思います。
もちろん、assertion是正作業までの期間が開くほど差分の正確性は薄くなりますが…。以後のPRにnon-nullが含まれなければ差分はそのまま使えると思います。

このPR自体の寿命を延ばし、non-null assertionを可能な限り無くしたうえでmasterにマージする、という方針もあります。自分としては、PRの課題が大きくなりすぎること、その差分でpdi-broserユーザにデグレ―ションが発生したときのロールバックや検証コストの点で、異常系・正常系を問わず、処理の変更を伴うnon-null是正は別のPRで行いたい気持ちがあります。

2021-03-04 01:06 UTC, yu-ogi commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
はい、繰り返しになりますがおっしゃっている意味はわかりますし、作業方針としても妥当かと思います。なので

> **tsconfig.json の strict は無効のまま** にして、部分的に対応していったほうが良いのではないかと思います。

という提案をしております。

2021-03-05 03:59 UTC, xnv commented
別で議論しましたが、ogi さんの書かれているとおり一気に strict にするには話が大きすぎたので、次のように段階的に進めたいです:

- a) strict を構成するフラグのうち、無理なくできるもの (`--noImplicitAny` など) を有効にする
- b) `--strictNullChecks` や `--strictPropertyInitialization` など、個別に修正の妥当性の検討が必要なもの
- c) (b) のうち、JS レベルの変更 (＝リファクタリング) を伴う  or 伴うべきもの

2021-03-05 10:46 UTC, kamakiri01 commented on src/ResourceFactory.ts
> +		return this._surfaceFactory.createPrimarySurface(width, height, this._rendererCandidates!); // Platformなど外部から渡される
はい、tsconfig.json の strict を 無効のままにすることに自分は異論ないです。

https://github.com/akashic-games/pdi-browser/pull/108#issuecomment-791135095
上記でコメントいただいていますが、strict フラグ別に対応を進め、最終的に `strict: true` を有効にする方針で進めたいと思います。

2021-03-05 12:06 UTC, kamakiri01 commented
コメントいただいた通り、フラグに分ける方針とします。
このPRはクローズします。

2021-03-05 12:06 UTC, closed without merging