feat: follow pdi-types@1.4.0-beta.0
akashic-games/pdi-browser pull request #239
Opened 2022-08-02 08:11 UTC by yu-ogi

## このPullRequestが解決する内容
pdi-types@1.4.0-beta.0 に追従します。

2022-08-02 08:13 UTC, yu-ogi commented on src/ResourceFactory.ts
> +		return new DynamicSVGImageAsset(id, id, data);
暫定的に id を path として扱っています。
https://github.com/akashic-games/pdi-types/pull/38 で修正予定です。

2022-08-04 09:00 UTC, xnv commented on src/asset/DynamicSVGImageAsset.ts
> +		const base64SVG = btoa(decodeURIComponent(encodeURIComponent(new XMLSerializer().serializeToString(inlineSVG))));
encode して decode したら元に戻りそうですが、これはどういう状況でこれが必要でしょうか？　また `inlineSVG` をシリアライズしたものはほとんど `svgString` に思いますが、

```typescript
btoa(svgString)
```

では済まないんでしょうか？　見た感じ `"xmlns"` の問題こそありますが、それのためにここまでする (一回パースしたのを文字列に戻してさらに URL エンコードして戻す) ぐらいなら 「 `"xmlns"` は必須です」って言い切ってしまう方が簡潔に思えます。(width/height 同様にエラーにしてしまうことはできるでしょうし)

2022-08-04 09:00 UTC, xnv commented on src/asset/DynamicSVGImageAsset.ts
> +export class DynamicSVGImageAsset extends SVGImageAsset {
用語は揃えたいので `GeneratedSVGImageAsset` にしときませんか。(そんなにいい語だとは思いませんが、語法の一貫性を考えて)

2022-08-08 04:54 UTC, yu-ogi commented on src/asset/DynamicSVGImageAsset.ts
> +export class DynamicSVGImageAsset extends SVGImageAsset {
こちら akashic-engine 側に追従する前の状態でした。修正済みです。

2022-08-08 04:56 UTC, yu-ogi commented on src/asset/DynamicSVGImageAsset.ts
> +		const base64SVG = btoa(decodeURIComponent(encodeURIComponent(new XMLSerializer().serializeToString(inlineSVG))));
xmlns はこのレイヤーで関知すべきではないと考え直して直接 `btoa()` 関数を実行するように修正しました。

2022-08-08 06:54 UTC, dera- commented on src/asset/GeneratedSVGImageAsset.ts
> +	return /^[0-9.]+(?:px)?$/.test(value);
こちらの正規表現は暫定という形で後から修正を入れる前提ということですかね

2022-08-08 06:54 UTC, dera- commented on CHANGELOG.md
> +* @akashic/pdi-types@1.4.0-beta.0 に追従
細かいですが、`@akashic/pdi-types@1.4.0-beta.1`ですかね

2022-08-08 07:02 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +	return /^[0-9.]+(?:px)?$/.test(value);
いえ、こちらの値の妥当性はゲーム開発者側が持つべきなのでこれ以上に厳密なチェックは特に行わない予定です。

2022-08-08 07:03 UTC, yu-ogi commented on CHANGELOG.md
> +* @akashic/pdi-types@1.4.0-beta.0 に追従
修正しました。ありがとうございます。

2022-08-08 07:22 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +	return /^[0-9.]+(?:px)?$/.test(value);
[b49a1c2](https://github.com/akashic-games/pdi-browser/pull/239/commits/b49a1c207f76c3cfbb08e86e25d9efae9e35f8e3)
と思いましたが指数表記に対応できていなかったためより厳密に修正しました。

2022-08-08 07:29 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +		}
外部リソースが canvas に描画されるわけではないためこのパスが必要なのか少し悩ましいです。

2022-08-09 03:18 UTC, dera- approved these changes

2022-08-09 10:06 UTC, xnv approved these changes

2022-08-09 10:06 UTC, xnv commented on src/asset/GeneratedSVGImageAsset.ts
> +	return /^[+-]?[0-9]+(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?(?:px)?$/.test(value);
- `".1px"` に誤って false を返しませんか。この箇所に仕様への完全な準拠が必要とは思いませんが、false positive (妥当なものを我々がエラーにしてしまう) は避けたいように思います。
- こだわりませんが、 `[0-9]` は `\d` とも [書けます][charclass] 。

[charclass]: https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

2022-08-09 10:06 UTC, xnv commented on src/asset/GeneratedSVGImageAsset.ts
> +			this.height = Math.ceil(parseFloat(stringHeight));
これ切り上げるのは必須なんですっけ……？　ラスタライズ時の canvas は切り上げるしかないと思いますが、ここで切り上げるべきかは自明ではなさそうに思いますが。

2022-08-09 10:06 UTC, xnv requested changes
すいません間違って approve しちゃいましたが切り上げの必要性は確認しておきたいです。

2022-08-10 01:37 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +		}
[744d921](https://github.com/akashic-games/pdi-browser/pull/239/commits/744d921518d1e565106b49bee85b7549a993c5b3) ということで削除しました。

2022-08-10 01:38 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +			this.height = Math.ceil(parseFloat(stringHeight));
[241751f](https://github.com/akashic-games/pdi-browser/pull/239/commits/241751fab3254fedd5664b9208aa14b03fddb781) たしかに自明ではないので切り上げは行わないように修正しました。

2022-08-10 01:40 UTC, yu-ogi commented on src/asset/GeneratedSVGImageAsset.ts
> +	return /^[+-]?[0-9]+(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?(?:px)?$/.test(value);
[f1e623d](https://github.com/akashic-games/pdi-browser/pull/239/commits/f1e623d9c95712d3ce8e1f016f1273aba003921e) [こちら](https://www.w3.org/TR/css-syntax-3/#typedef-number-token)を参考にもう少し厳格にチェックするようにしました。

2022-08-10 02:22 UTC, xnv approved these changes

2022-08-10 03:15 UTC, merged